# Site settings
title: Material de Arquitecturas Concurrentes
header-img: img/home-bg.jpg
description: "Material de la materia de Arquitecturas concurrentes en forma de libro"
baseurl: ""
relative_url: ""
url: ""
github_username: "arquitecturas-concurrentes"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: blog/page:num
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: ['jekyll-paginate', 'rouge']