# TODO: Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    environment:
      TZ: "/usr/share/zoneinfo/America/Argentina/Buenos_Aires"
    paralelism: 2
    steps:
      - add_ssh_keys:
          fingerprints:
          - "79:96:ed:b0:38:b2:d7:03:5f:94:96:96:cc:6c:08:ed"
      - run: git config --global user.email "iasc.bot@gmail.com"
      - run: git config --global user.name "IASCBotCI"
      - checkout
      - run:
          name: APT Installs
          command: |
            sudo apt-get update
            sudo apt-get install build-essential patch
            sudo apt-get install ruby-dev zlib1g-dev liblzma-dev libgmp-dev cmake
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Install dependencies
          command: bundle install --jobs=10 --retry=3
      - run:
          name: Run the tests for backend
          command: bundle exec rake test
      - run:
          name: Publishing
          command: bundle exec rake publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: source